module.exports = {
  //USER MESSAGES
  USER_CREATED: "USER CREATED",
  USER_CREATED_FAIL: "USER NOT CREATED",
  USER_UPDATED: "USER UPDATED",
  USER_UPDATED_FAIL: "USER NOT UPDATED",
  USER_DELETED: "USER DELETED",
  USER_DELETED_FAIL: "USER NOT DELETED",
  USERS_FOUND: "USERS FOUND",
  USERS_NOT_FOUND: "USERS NOT FOUND",
  USER_FOUND: "USER NOT FOUND",
  //LOGIN MESSAGES
  INVALID_PASSWORD: "INVALID PASSWORD",
  USER_CONNECTED: "USER CONNECTED",
  //LOGOUT MESSAGES
  USER_DECONNECTED: "USER DECONNECTED",
  USER_NOT_CONNECTED: "YOU'RE NOT LOGGED IN",
  //MIDDLEWARE MESSAGES
  TOKEN_REQUIRED: "TOKEN REQUIRED",
  INVALID_TOKEN: "INVALID TOKEN",
  UNAUTHORIZED: "ANAUTHORIZED",
};
